### ISSUE TITLE
Use binary format for loading matrices

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ldbc-graphalytics#12]
`LAGraph_grread` support loading graphs in Galois format. These (I think) can be generated 
with the Galois library's [`galois::graphs::FileGraph::toFile` method](https://iss.oden.utexas.edu/projects/galois/api/current/classgalois_1_1graphs_1_1FileGraph.html). LAGraph supports reading graphs but does not yet support generating these, see: https://github.com/GraphBLAS/LAGraph/blob/b5f047e600773f686b5f2f2e40f9af6f67d4231c/TODO.txt#L30

**Comment by hegyibalint** [comment]
What is the advised way of transforming our source graphs to this format?
Currently we use our Julia-based converter for MM, but I see no appropriate binding for Galois.

**Comment by szarnyasg** [comment]
Probably this library - https://iss.oden.utexas.edu/projects/galois/api/current/classgalois_1_1graphs_1_1FileGraph.html
But this is not a high-priority issue - eventually, LAGraph will provide built-in support for this format.

**Comment by hegyibalint** [comment]
But even in that case, we would need to convert the raw datasets into remapped matrices, and this is an obvious conversion step.
You mean by LAGraph support to not write a converter directly to Galois format, but follow the `Graphalytics -[converter]-> MM -[LAGraph serializer]-> Galois binary` chain?

**Comment by szarnyasg** [comment]
> You mean by LAGraph support to not write a converter directly to Galois format, but follow the `Graphalytics -[converter]-> MM -[LAGraph serializer]-> Galois binary` chain?

Yes - we only need to do this once.

**Comment by szarnyasg** [comment]
`LAGraph_binread` and `LAGraph_binwrite` are now out! https://github.com/GraphBLAS/LAGraph/tree/master/Source/Utility

**Comment by szarnyasg** [comment]
Done!
