### ISSUE TITLE
DuckDB 0.10.0 Doesn't Have the Option Named "experimental_parallel_csv"

### ISSUE THREAD

**Issue by SakuraMarble** [FTSRG/ldbc-graphalytics#45]
**The newest and default version of duckdb downloaded by  pip install is  0.10.0.There is no setting named "experimental_parallel_csv".It was available at 0.6.0 by my test.**

  File "/home/mabj/ldbc_graphalytics_platforms_graphblas/graphalytics-1.10.0-graphblas-0.1.0-SNAPSHOT/bin/py/relabel.py", line 26
    con.execute(f"SET experimental_parallel_csv=true")
                                                      ^
IndentationError: unindent does not match any outer indentation level
18:54 [ERROR] Failed to load graph ""graph500-22:graph500-22"".

**However even when I downgraded the version to 0.6.0,I still had difficulty in correcty importing the datasets.But I didn't know why.**

17:38 [ERROR] [Runner r568788] => 17:38 [ERROR] Algorithm "Breadth first search" on graph "graph500-22 failed to complete:
17:38 [ERROR] A benchmark failure (EXE) is caught by the runner.
17:39 [ERROR] [Runner r754132] => 17:39 [ERROR] Vertex count is incorrect, expected: 2396657, actual: 0
17:39 [ERROR] A benchmark failure (VAL) is caught by the runner.

**So in the end,I commented out the line containing "experimental_parrallel_csv" in relabel.py and everything went well.**

19:04 [INFO ] In total, [15 / 15] benchmark(s) succeed.

**Hope my experience will be helpful to the greenhands like me.**

**Comment by szarnyasg** [comment]
Thanks! I fixed this this now via c0bcb6873fe35ad8268d3e25d67b54f523bf0a4e
