### ISSUE TITLE
/bin/sh/exe/$ALGORITHMS  Where is /bin/sh/exe?

### ISSUE THREAD

**Issue by seongyongbaek** [FTSRG/ldbc-graphalytics#46]
I will Benchmark OrientDB used LDBC_Graphalytics.
then I Script /bin/sh/execute.sh
case $ALGORITHM in
    bfs)
      COMMAND="$rootdir/bin/exe/$ALGORITHM --jobid $JOB_ID \
        --root $SOURCE_VERTEX \
        --dataset $INPUT_PATH --output $OUTPUT_PATH \
        --threadnum $NUM_THREADS"
      ;;

Then I wondering How to setting exe Dir and how to scripts Algorithms file like pr, bfs, wcc

**Comment by szarnyasg** [comment]
Run `./init.sh`, then the `bin/exe` directory will be available in the `graphalytics-1.10.0-graphblas-0.1.0-SNAPSHOT` directory.
